version: "3.7"
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=1
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
    ports:
      - "8080:80"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: library/mysql:8.0.20
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-datavolume:/var/lib/mysql
  adminer:
    container_name: fluentanalytics-db-viewer
    image: adminer
    ports:
      - 8081:8080
volumes:
  my-datavolume: